### PR TITLE
Allow to override default rasterizer DPI parameters

### PR DESCRIPTION
**Pull request by turowicz**
Needed to get better rendering results for text documents.

Related #3

### CODE REVIEW

**Comment by turowicz** [comment]
@dampee please review :)

**Comment by dampee** [comment]
Hi, 
It seems you have not done any change to the PdfRasterizer class.  Could you update so that the file does not appears to be changed? in the pull request?
Kind regards
Damiaan

**Comment by turowicz** [comment]
It has incorrect line endings, that's why you don't see any difference in diff.

Will revert it. I've also noticed some other problems with how ImageProcessor instantiates PdfFormat... Will submit some new changes tomorrow.

**Comment by dampee** [comment]
Cool, thans! Please keep different issues in different PR's.

Op 17 jul. 2017 9:39 p.m. schreef Wojtek Turowicz <notifications@github.com>:

It has incorrect line endings, that's why you don't see any difference in diff.

Will revert it. I've also noticed some other problems with how ImageProcessor instantiates PdfFormat... Will submit some new changes tomorrow.

**Comment by turowicz** [comment]
@dampee I've reverted the line endings. Strange that you keep one file in CR and another CRLF but that's up to you.

I've also changed the constructor of PdfFormat as it needs to be parameterless, otherwise ImageProcessor throws exceptions.

Hope this is good enough, thanks!

**Pull request merged**
